// Build script: runs typecheck, then Tailwind CLI to generate CSS, then inlines it
// into a TS module so it gets bundled into the serverless function.
import { $ } from "bun";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

// 0. Typecheck — fail fast on type errors before building.
// Uses tsconfig.json which excludes auto-generated and broken files.
console.log("Running typecheck (tsc --noEmit)...");
await $`bunx tsc --noEmit --project tsconfig.json`;
console.log("Typecheck passed.");

// 1. Generate CSS with Tailwind CLI.
await $`bunx @tailwindcss/cli -i src/input.css -o public/css/app.css --minify`;

// 2. Read the generated CSS and write it as a TS module.
const css = readFileSync("public/css/app.css", "utf-8");
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/css.ts",
  `// AUTO-GENERATED by scripts/build.ts -- do not edit.\nexport const appCss = ${JSON.stringify(css)};\n`,
);

console.log(`CSS built and inlined: ${css.length} bytes -> src/generated/css.ts`);
