// Build script: generates CSS first (so typecheck can find the module),
// then runs typecheck, then bundles the app into a single JS file for Vercel.
import { $ } from "bun";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

// 1. Generate CSS with Tailwind CLI.
console.log("Generating CSS with Tailwind...");
await $`bunx @tailwindcss/cli -i src/input.css -o public/css/app.css --minify`;

// 2. Read the generated CSS and write it as a TS module.
const css = readFileSync("public/css/app.css", "utf-8");
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/css.ts",
  `// AUTO-GENERATED by scripts/build.ts -- do not edit.\nexport const appCss = ${JSON.stringify(css)};\n`,
);
console.log(`CSS built and inlined: ${css.length} bytes -> src/generated/css.ts`);

// 3. Typecheck — now that css.ts exists, tsc can resolve all imports.
console.log("Running typecheck (tsc --noEmit)...");
await $`bunx tsc --noEmit --project tsconfig.json`;
console.log("Typecheck passed.");

// 4. Bundle the app into a single JS file for Vercel serverless.
// This avoids the "Requested module is not instantiated yet" Bun runtime bug
// on Vercel, which happens with ESM/CJS interop in the module graph.
console.log("Bundling app for Vercel...");
await $`bun build src/index.ts --outdir .vercel/output --target bun --format esm --external @supabase/supabase-js`;
console.log("Bundle written to .vercel/output/index.js");
