// Build script: generates CSS, runs typecheck, then bundles the app into
// a single JS file for Vercel serverless (Node.js runtime).
// Bundling is required because Node.js ESM requires file extensions in
// imports, but our codebase uses extensionless imports (Bun-style).
import { $ } from "bun";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

// 1. Generate CSS with Tailwind CLI.
console.log("Generating CSS with Tailwind...");
await $`bunx @tailwindcss/cli -i src/input.css -o public/css/app.css --minify`;

// 2. Read the generated CSS and write it as a TS module.
const css = readFileSync("public/css/app.css", "utf-8");
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/css.ts",
  `// AUTO-GENERATED by scripts/build.ts -- do not edit.\nexport const appCss = ${JSON.stringify(css)};\n`,
);
console.log(`CSS built and inlined: ${css.length} bytes -> src/generated/css.ts`);

// 3. Typecheck — now that css.ts exists, tsc can resolve all imports.
console.log("Running typecheck (tsc --noEmit)...");
await $`bunx tsc --noEmit --project tsconfig.json`;
console.log("Typecheck passed.");

// 4. Bundle the app into a single JS file for Vercel.
// Target node, ESM format. All dependencies are bundled except node builtins.
console.log("Bundling app for Vercel (Node.js ESM)...");
await $`bun build src/server/app.ts --outfile src/generated/bundle.js --target node --format esm --external @supabase/supabase-js --external hono`;
console.log("Bundle written to src/generated/bundle.js");
