// Standalone CSS generation — generates src/generated/css.ts without typecheck.
// Used in CI before typecheck (since css.ts is gitignored but imported by .tsx files).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

await Bun.spawn(["bunx", "@tailwindcss/cli", "-i", "src/input.css", "-o", "public/css/app.css", "--minify"], { stdout: "inherit", stderr: "inherit" }).exited;

const css = readFileSync("public/css/app.css", "utf-8");
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/css.ts",
  `// AUTO-GENERATED by scripts/gen-css.ts -- do not edit.\nexport const appCss = ${JSON.stringify(css)};\n`,
);

console.log(`CSS generated: ${css.length} bytes -> src/generated/css.ts`);
