// Vercel serverless entry point.
// Imports the pre-bundled app (generated by scripts/build.ts).
// The bundle is a single JS file with all deps inlined, avoiding
// Node.js ESM extension issues.
// @ts-expect-error — generated file, no type declarations
export { default } from "../src/generated/bundle.js";
