// Vercel serverless entry point.
// Imports the pre-bundled app (generated by scripts/build.ts).
// The bundle is a single JS file with all deps inlined, avoiding
// Node.js ESM extension issues.
// The `hono` import below is required for Vercel's Hono framework
// detection — without it, Vercel cannot identify the entrypoint and
// fails with "No entrypoint found which imports hono".
import { Hono } from "hono";
// @ts-ignore — generated file, no type declarations
import app from "../src/generated/bundle.js";

export default app as unknown as Hono;
